.TH "mate-appearance-properties" "1" 

.SH "NAME" 
mate-appearance-properties \(em is a control center applet. 

.SH "SYNOPSIS" 
.PP 
\fBmate-appearance-properties\fR [\fIOPTIONS\fR]... [\fIWALLPAPER\fR]...

.SH "DESCRIPTION" 
.PP 
MATE Appearance Properties is a control center applet to edit appearance
settings.
.PP
It allows one to change: GTK theme, window manager theme, icon theme, cursor
theme, desktop background and font settings. 

.SH "OPTIONS" 
.PP 
.IP "\fB-i,\fP  \fB\-\-install-theme=\fIFILENAME\fR\fP " 10 
Specify the filename of a theme to install
.PP 
.IP "\fB-p,\fP  \fB\-\-show-page=\fIPAGE\fR\fP " 10 
Specify the name of the page to show (theme|background|fonts|interface)

.SH "AUTHOR" 
.PP 
This manual page was written by Stefano Karapetsas <stefano@karapetsas.com>.
