.\" Copyright (C) 2014 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH mate-network-properties 1 "2014\-05\-02" "MATE"
.SH NAME
mate-network-properties \- configure MATE network proxy
.SH SYNOPSIS
.B mate-network-properties
.RI [ OPTIONS... ]
.SH DESCRIPTION
This executable is part of the package 'mate\-control\-center': The MATE Control Center.
.PP
The MATE network proxy preference tool enables you to configure how
your system connects to networks. You can configure the desktop to
connect to a proxy server, and specify the details of the proxy server.
.PP
A proxy server is a server that intercepts requests to another server,
and fulfills the request itself, if it can. You can enter the Domain
Name Service (DNS) name or the Internet Protocol (IP) address of the
proxy server.
.SH OPTIONS
This program accepts the standard MATE and GTK options.
.SH AUTHORS
.B mate-network-properties
This manual page was writtenby Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
for the Debian project (but may be used by others).
.SH SEE ALSO
Latest version of the MATE Desktop User Guide for your platform.
.PP
.BR "mate-control-center" (1),
.BR "gtk-options" (7)
