.TH "mate-default-applications-properties" "1" 

.SH "NAME" 
mate-default-applications-properties \(em is a control center applet. 

.SH "SYNOPSIS" 
.PP 
\fBmate-default-applications-properties\fR [\fIOPTIONS\fR]...

.SH "DESCRIPTION" 
.PP 
MATE Default Applications Properties is a control center applet to edit
default applications.
.PP
It allows one to set default file manager, email client, web browser, etc. 

.SH "OPTIONS" 
.PP 
.IP "\fB-p,\fP  \fB\-\-show-page=\fIPAGE\fR\fP " 10 
Specify the name of the page to show (internet|multimedia|system|a11y)

.SH "AUTHOR" 
.PP 
This manual page was written by Stefano Karapetsas <stefano@karapetsas.com>.
