.\" Copyright (C) 2014 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH "mate\-at\-properties" "1" "2014\-05\-02" "MATE"
.\"
.SH "NAME"
mate-at-properties \- configure MATE Assistive Technologies
.SH "SYNOPSIS"
.B mate-at-properties
.RI [ OPTIONS...]
.SH "DESCRIPTION"
This executable is part of the package 'mate\-control\-center': The MATE Control Center.
.PP
The MATE Assistive Technology preference is used to enable assistive technologies in your
desktop. You can use gnome-at-properties to specify that the following assistive  technology
applications start automatically when you log in:
.PP
  o Screenreader

  o Magnifier

  o On-screen Keyboard
.SH OPTIONS
This program accepts the standard MATE and GTK options.
.SH "SEE ALSO"
.PP
Latest version of the MATE Desktop User Guide for your platform.
.PP
.BR "mate-control-center" (1),
.BR "gtk-options" (7),
