name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. If the issue is still valid, please comment or update it. Otherwise, it will be closed in 7 days.'
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. If the pull request is still valid, please comment or update it. Otherwise, it will be closed in 7 days.'
          days-before-stale: 365 # Number of days of inactivity before an issue is marked as stale
          days-before-close: 7 # Number of days to wait to close an issue after it has been marked as stale
          exempt-issue-labels: 'never-stale' # Label to exempt issues from being marked as stale
          exempt-pr-labels: 'never-stale' # Label to exempt pull requests from being marked as stale
